### ISSUE TITLE
Volver a jugar

### ISSUE THREAD

**Issue by IsmaelQR** [JhonCusi/Trivia-de-Jhon-cusi#1]
https://github.com/JhonCusi/Trivia-de-Jhon-cusi/blob/b693d55c4acc6783578ad58ffc911b1ba24dc5e3/main.py#L94
### Sigamos jugando
Sería genial poder volver a jugar para obtener mas puntuaciones   y poder **disfrutarlo más**.

**Comment by JhonCusi** [comment]
gracias
